export const data = [

	{
		id: 1,
		property_type: 'Government',
		name: 'Government',
		activity: 'Compound House',
		landmark:'District Office',
		house_number:'GR 4320',
		proerty_rate:50,
		payment_type:'Yearly',
		mobile_number:'0549993994',
	},
	{
		id: 2,
		property_type: 'Residential',
		name: 'Maa Sarpong',
		activity: 'Compound House',
		landmark:'District Office',
		house_number:'GR 4320',
		proerty_rate:50,
		payment_type:'Yearly',
		mobile_number:'0549993994',
	},
	{
		id: 3,
		property_type: 'Residential',
		name: 'Maa Sarpong',
		activity: 'Compound House',
		landmark:'District Office',
		house_number:'GR 4320',
		proerty_rate:50,
		payment_type:'Yearly',
		mobile_number:'0549993994',
	},
	{
		id: 4,
		property_type: 'Residential',
		name: 'Maa Sarpong',
		activity: 'Compound House',
		landmark:'District Office',
		house_number:'GR 4320',
		proerty_rate:50,
		payment_type:'Yearly',
		mobile_number:'0549993994',
	}
];
